ME-Model-ID: senterica
growth_key: mu1
complex_cofactors:
  fes_transfers:
  - STM0204-MONOMER
  - STM1369-MONOMER
  - STM2541-MONOMER
  biotin_subreactions:
    mod_btn_c:
    - biotin_ligase
  lipoate_subreactions:
    mod_lipoyl_c:
    - lipoyl_denovo
    - lipoyl_scavenging
  fes_chaperones: {}
  bmocogdp_chaperones: {}
  FeFe/NiFe:
    mod_FeFe_cofactor_c: ''
    mod_NiFe_cofactor_c: ''
lipoprotein_precursors:
  AcrA: STM0476
  AcrE: STM3390
  BamB: STM2520
  BamC: STM2488
  BamD: STM2663
  BamE: STM2685
  CusC: STM0350
  EG10544-MONOMER: STM1377
  EmtA: STM1799
  LolB: STM1778
  MetQ: STM0245
  MltA: STM2988
  MltB: STM2831
  MltC: STM3112
lipid_modifications:
- pg160_p
- pg120_p
- pg140_p
- pg141_p
- pg161_p
- pg180_p
- pg181_p
unmodeled_protein_fraction: 0.36
flux_of_biomass_constituents: {}
flux_of_lipid_constituents: {}
braun's_lipoprotein: []
braun's_lpp_flux: -0.0
braun's_murein_flux: -0.0
gr_data_doublings_per_hour:
- 0
- 0.6
- 1.0
- 1.5
- 2.0
- 2.5
percent_dna_data:
- 0.0592
- 0.0512
- 0.033
- 0.0252
- 0.0222
- 0.0208
defer_to_rxn_matrix:
- BIOMASS_iRR1083_metals
- FMETTRS
- ATPM
m-model-path: ./senterica//building_data/m_model_modified.json
genbank-path: ./senterica//building_data/genome_modified.gb
biocyc.genes: ./senterica/inputs/genes.txt
biocyc.prots: ./senterica/inputs/proteins.txt
biocyc.TUs: ./senterica/inputs/TUs.txt
biocyc.RNAs: ./senterica/inputs/RNAs.txt
biocyc.seqs: ./senterica/inputs/sequences.fasta
df_gene_cplxs_mods_rxns: ./senterica/building_data/automated-org-with-refs.xlsx
df_TranscriptionalUnits: ./senterica//building_data/TUs_from_biocyc.txt
out_directory: ./senterica/
log_directory: ./senterica/
run_bbh_blast: false
dev_reference: false
include_pseudo_genes: true
selenocysteine_enzymes:
- CPLX_dummy
pg_pe_160:
- STM3002-MONOMER
- STM0047-MONOMER
other_lipids:
- STM0666-MONOMER
default_sigma_factor: STM4165-MONOMER
rna_polymerases:
  RNAP_STM3320MONOMER:
    sigma_factor: STM3320-MONOMER
    polymerase: CPLX1R65-35_mod_zn2(1)_mod_mg2(2)
  RNAP_STM2924MONOMER:
    sigma_factor: STM2924-MONOMER
    polymerase: CPLX1R65-35_mod_zn2(1)_mod_mg2(2)
  RNAP_STM3211MONOMER:
    sigma_factor: STM3211-MONOMER
    polymerase: CPLX1R65-35_mod_zn2(1)_mod_mg2(2)
  RNAP_STM4165MONOMER:
    sigma_factor: STM4165-MONOMER
    polymerase: CPLX1R65-35_mod_zn2(1)_mod_mg2(2)
  RNAP_STM3568MONOMER:
    sigma_factor: STM3568-MONOMER
    polymerase: CPLX1R65-35_mod_zn2(1)_mod_mg2(2)
  RNAP_STM2640MONOMER:
    sigma_factor: STM2640-MONOMER
    polymerase: CPLX1R65-35_mod_zn2(1)_mod_mg2(2)
  RNAP_STM1956MONOMER:
    sigma_factor: STM1956-MONOMER
    polymerase: CPLX1R65-35_mod_zn2(1)_mod_mg2(2)
ngam: 8.39
gam: 59.81
translocation_multipliers:
  STM3842-MONOMER:
    STM1889: 2.0
    STM3864: 2.0
  STM0632-MONOMER:
    STM4279: 20.0
    STM1569: 5.166666666666667
    STM1570: 5.166666666666667
    STM2991: 22.0
    STM1787: 14.0
    STM1786: 14.0
    STM3822: 13.5
    STM4036: 15.5
    STM0193: 21.0
    STM4037: 15.5
    STM1498: 15.0
    STM3086: 6.25
    STM1499: 14.0
    STM3150: 14.0
    STM3149: 21.0
    STM3147: 14.0
    STM2450: 20.0
    STM0964: 26.0
    STM0168: 23.0
    STM2259: 27.0
    STM2258: 20.0
  STM3973-MONOMER:
    STM4279: 20.0
    STM1569: 5.166666666666667
    STM1570: 5.166666666666667
    STM2991: 22.0
    STM1787: 14.0
    STM1786: 14.0
    STM3822: 13.5
    STM4036: 15.5
    STM0193: 21.0
    STM4037: 15.5
    STM1498: 15.0
    STM3086: 6.25
    STM1499: 14.0
    STM3150: 14.0
    STM3149: 21.0
    STM3147: 14.0
    STM2450: 20.0
    STM0964: 26.0
    STM0168: 23.0
    STM2259: 27.0
    STM2258: 20.0
amino_acid_trna_synthetase:
  ala__L_c: STM2827-MONOMER
  arg__L_c: STM1909-MONOMER
  asn__L_c: STM1000-MONOMER
  asp__L_c: STM1901-MONOMER
  cys__L_c: STM0537-MONOMER
  gln__L_c: STM0686-MONOMER
  glu__L_c: STM2415-MONOMER
  gly_c: CPLX1R65-25
  his__L_c: STM2522-MONOMER
  ile__L_c: STM0046-MONOMER
  leu__L_c: STM0648-MONOMER
  lys__L_c: STM3040-MONOMER
  met__L_c: STM2155-MONOMER
  phe__L_c: CPLX1R65-3
  pro__L_c: STM0242-MONOMER
  ser__L_c: STM0963-MONOMER
  thr__L_c: STM1333-MONOMER
  trp__L_c: generic_trp_ligase
  tyr__L_c: STM1449-MONOMER
  val__L_c: STM4475-MONOMER
peptide_release_factors:
  UAG: STM1776-MONOMER
  UGA: STM3041-MONOMER
  UAA: generic_RF
braun's_lipoproteins:
- STM1377-MONOMER
