ME-Model-ID: synechocystis
growth_key: mu1
complex_cofactors:
  fes_transfers:
  - SGL_RS02730-MONOMER
  biotin_subreactions:
    mod_btn_c:
    - biotin_ligase
  lipoate_subreactions:
    mod_lipoyl_c:
    - lipoyl_denovo
    - lipoyl_scavenging
  fes_chaperones: {}
  bmocogdp_chaperones: {}
  FeFe/NiFe:
    mod_FeFe_cofactor_c: ''
    mod_NiFe_cofactor_c: ''
lipoprotein_precursors:
  MltA: SGL_RS13395
lipid_modifications: []
unmodeled_protein_fraction: 0.36
flux_of_biomass_constituents: {}
flux_of_lipid_constituents: {}
braun's_lipoprotein: []
braun's_lpp_flux: -0.0
braun's_murein_flux: -0.0
gr_data_doublings_per_hour:
- 0
- 0.6
- 1.0
- 1.5
- 2.0
- 2.5
percent_dna_data:
- 0.0592
- 0.0512
- 0.033
- 0.0252
- 0.0222
- 0.0208
defer_to_rxn_matrix:
- BIOMASS_Ec_SynAuto_3
- FMETTRS
- ATPM
m-model-path: ./synechocystis//building_data/m_model_modified.json
genbank-path: ./synechocystis//building_data/genome_modified.gb
biocyc.genes: ./synechocystis/inputs/genes.txt
biocyc.prots: ./synechocystis/inputs/proteins.txt
biocyc.TUs: ./synechocystis/inputs/TUs.txt
biocyc.RNAs: ./synechocystis/inputs/RNAs.txt
biocyc.seqs: ./synechocystis/inputs/sequences.fasta
df_gene_cplxs_mods_rxns: ./synechocystis/building_data/automated-org-with-refs.xlsx
df_TranscriptionalUnits: ./synechocystis//building_data/TUs_from_biocyc.txt
out_directory: ./synechocystis/
log_directory: ./synechocystis/
run_bbh_blast: false
dev_reference: false
include_pseudo_genes: true
feasibility_mu: 0.005
selenocysteine_enzymes:
- CPLX_dummy
pg_pe_160:
- SGL_RS03335-MONOMER
- SGL_RS07065-MONOMER
other_lipids:
- SGL_RS09925-MONOMER
rna_polymerases:
  RNAP_SGLRS12540MONOMER:
    sigma_factor: SGL_RS12540-MONOMER
    polymerase: CPLX220H-12_mod_zn2(1)_mod_mg2(2)
  RNAP_SGLRS08165MONOMER:
    sigma_factor: SGL_RS08165-MONOMER
    polymerase: CPLX220H-12_mod_zn2(1)_mod_mg2(2)
  RNAP_SGLRS17245MONOMER:
    sigma_factor: SGL_RS17245-MONOMER
    polymerase: CPLX220H-12_mod_zn2(1)_mod_mg2(2)
  RNAP_SGLRS17440MONOMER:
    sigma_factor: SGL_RS17440-MONOMER
    polymerase: CPLX220H-12_mod_zn2(1)_mod_mg2(2)
  RNAP_SGLRS14610MONOMER:
    sigma_factor: SGL_RS14610-MONOMER
    polymerase: CPLX220H-12_mod_zn2(1)_mod_mg2(2)
  RNAP_SGLRS06480MONOMER:
    sigma_factor: SGL_RS06480-MONOMER
    polymerase: CPLX220H-12_mod_zn2(1)_mod_mg2(2)
  RNAP_SGLRS07975MONOMER:
    sigma_factor: SGL_RS07975-MONOMER
    polymerase: CPLX220H-12_mod_zn2(1)_mod_mg2(2)
  RNAP_SGLRS07740MONOMER:
    sigma_factor: SGL_RS07740-MONOMER
    polymerase: CPLX220H-12_mod_zn2(1)_mod_mg2(2)
  RNAP_SGLRS14165MONOMER:
    sigma_factor: SGL_RS14165-MONOMER
    polymerase: CPLX220H-12_mod_zn2(1)_mod_mg2(2)
ngam: 1.0
gam: 53.35
translocation_multipliers:
  SGL_RS10510-MONOMER: {}
amino_acid_trna_synthetase:
  ala__L_c: SGL_RS11990-MONOMER
  arg__L_c: SGL_RS16720-MONOMER
  asn__L_c: SGL_RS16775-MONOMER
  asp__L_c: SGL_RS08775-MONOMER
  cys__L_c: SGL_RS11450-MONOMER
  gln__L_c: CPLX_dummy
  glu__L_c: SGL_RS14665-MONOMER
  gly_c: CPLX-tRNA-GLY-LIGASE
  his__L_c: SGL_RS13330-MONOMER
  ile__L_c: SGL_RS06865-MONOMER
  leu__L_c: SGL_RS05615-MONOMER
  lys__L_c: SGL_RS06545-MONOMER
  met__L_c: SGL_RS14365-MONOMER
  phe__L_c: CPLX-tRNA-PHE-LIGASE
  pro__L_c: SGL_RS09270-MONOMER
  ser__L_c: SGL_RS05225-MONOMER
  thr__L_c: SGL_RS15335-MONOMER
  trp__L_c: SGL_RS07690-MONOMER
  tyr__L_c: SGL_RS04920-MONOMER
  val__L_c: SGL_RS16980-MONOMER
peptide_release_factors:
  UAG: SGL_RS18110-MONOMER
  UGA: SGL_RS12270-MONOMER
  UAA: generic_RF
braun's_lipoproteins: []
