ME-Model-ID: staph
growth_key: mu1
complex_cofactors:
  fes_transfers:
  - USA300HOU_RS04660-MONOMER
  biotin_subreactions:
    mod_btn_c:
    - biotin_ligase
  lipoate_subreactions:
    mod_lipoyl_c:
    - lipoyl_denovo
    - lipoyl_scavenging
  fes_chaperones: {}
  bmocogdp_chaperones: {}
  FeFe/NiFe:
    mod_FeFe_cofactor_c: ''
    mod_NiFe_cofactor_c: ''
lipoprotein_precursors:
  MetQ: USA300HOU_RS04415
lipid_modifications: []
unmodeled_protein_fraction: 0.36
flux_of_biomass_constituents: {}
flux_of_lipid_constituents: {}
braun's_lipoprotein: []
braun's_lpp_flux: -0.0
braun's_murein_flux: -0.0
gr_data_doublings_per_hour:
- 0
- 0.6
- 1.0
- 1.5
- 2.0
- 2.5
percent_dna_data:
- 0.0592
- 0.0512
- 0.033
- 0.0252
- 0.0222
- 0.0208
defer_to_rxn_matrix:
- BIOMASS_iYS_wild_type
- FMETTRS
- ATPM
m-model-path: ./staph//building_data/m_model_modified.json
genbank-path: ./staph//building_data/genome_modified.gb
biocyc.genes: ./staph/inputs/genes.txt
biocyc.prots: ./staph/inputs/proteins.txt
biocyc.TUs: ./staph/inputs/TUs.txt
biocyc.RNAs: ./staph/inputs/RNAs.txt
biocyc.seqs: ./staph/inputs/sequences.fasta
df_gene_cplxs_mods_rxns: ./staph/building_data/automated-org-with-refs.xlsx
df_TranscriptionalUnits: ./staph//building_data/TUs_from_biocyc.txt
out_directory: ./staph/
log_directory: ./staph/
run_bbh_blast: false
dev_reference: false
include_pseudo_genes: true
selenocysteine_enzymes:
- CPLX_dummy
pg_pe_160:
- USA300HOU_RS04120-MONOMER
- USA300HOU_RS06010-MONOMER
other_lipids: []
rna_polymerases:
  RNAP_USA300HOURS02810MONOMER:
    sigma_factor: USA300HOU_RS02810-MONOMER
    polymerase: CPLX2KSB-27_mod_zn2(1)_mod_mg2(2)
  RNAP_USA300HOURS11145MONOMER:
    sigma_factor: USA300HOU_RS11145-MONOMER
    polymerase: CPLX2KSB-27_mod_zn2(1)_mod_mg2(2)
  RNAP_USA300HOURS09435MONOMER:
    sigma_factor: USA300HOU_RS09435-MONOMER
    polymerase: CPLX2KSB-27_mod_zn2(1)_mod_mg2(2)
  RNAP_USA300HOURS08330MONOMER:
    sigma_factor: USA300HOU_RS08330-MONOMER
    polymerase: CPLX2KSB-27_mod_zn2(1)_mod_mg2(2)
ngam: 1.0
gam: 45.0
translocation_multipliers:
  USA300HOU_RS11290-MONOMER:
    USA300HOU_RS11355: 2.0
amino_acid_trna_synthetase:
  ala__L_c: USA300HOU_RS08615-MONOMER
  arg__L_c: USA300HOU_RS03230-MONOMER
  asn__L_c: USA300HOU_RS07440-MONOMER
  asp__L_c: USA300HOU_RS08675-MONOMER
  cys__L_c: USA300HOU_RS02790-MONOMER
  gln__L_c: CPLX_dummy
  glu__L_c: USA300HOU_RS02780-MONOMER
  gly_c: USA300HOU_RS08350-MONOMER
  his__L_c: USA300HOU_RS08680-MONOMER
  ile__L_c: USA300HOU_RS05995-MONOMER
  leu__L_c: USA300HOU_RS09335-MONOMER
  lys__L_c: USA300HOU_RS02655-MONOMER
  met__L_c: USA300HOU_RS02505-MONOMER
  phe__L_c: CPLX2KSB-34
  pro__L_c: USA300HOU_RS06365-MONOMER
  ser__L_c: USA300HOU_RS00045-MONOMER
  thr__L_c: USA300HOU_RS08915-MONOMER
  trp__L_c: USA300HOU_RS04940-MONOMER
  tyr__L_c: USA300HOU_RS09175-MONOMER
  val__L_c: USA300HOU_RS08810-MONOMER
peptide_release_factors:
  UAG: USA300HOU_RS11435-MONOMER
  UGA: USA300HOU_RS04080-MONOMER
  UAA: generic_RF
braun's_lipoproteins: []
